package
{
	public class Pics
	{

	public const ColPalette:Array = [
		0x669966, 0x008000, 0xffffff, 0x808080, 0xff0000, 
		0x800000, 0x000000, 0xffff80, 0xc0c0c0, 0xff8040, 
		0x804000, 0x004040, 0x80ffff, 0x2d2d2d, 0x9ed5e0, 
		0x008080, 0xffa8ff, 0x97ff97, 0xfdcd99, 0xa3f3d3, 
		0xf9fe89, 0x181818, 0x1e1e1e, 0x595959, 0x646464, 
		0xf4fd5b, 0xffff00, 0x6d6d6d, 0xf86861 ];


	/*
	 datas of pictures:
	 Skip right dx, Skip down dy, Width, Height, 
	 arrays of color bytes ('a'-transp., or ColPalette# 'b'=0,'c'=1,...,'z','A'=26,...)
	*/

public const white_king:Array = [ 1, 0, 34, 35, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaeeeeaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaefghaaaaaaaaaaaaaaa",
"aaaahhhhhaaaaaaefghaaaaaahhhhhaaaa",
"aaahhfgihhhaaaahgghaaaahhhifghhaaa",
"aahhihhhiihhhaahjehaahhhjihhhjhhaa",
"ahhiihjhhiijhhhhjehhhhjiihhehhjhha",
"ahijhjjjjhhjjjijfgeijjihhjjeehjeha",
"ahijhjjiiijhhhijfgehhhhjjjjjehjeha",
"ahijhjiiiiijjjhhgghhjjjiiijjehjeha",
"ahijhjiiiiiiijehjehjjiiiiijeehjeha",
"ahhihhjiiiiiijehjehjiiiiiijehhjhha",
"aahijhjiiiiiijehjehjiiiiiijehjjhaa",
"aahhjhhjiiiiijehjehjiiiiiijhhehhaa",
"aaahijhjiihhjjehjehjiihhiijhjhhaaa",
"aaahhihhjihfhjehjehjihfhijhhehhaaa",
"aaaahijhjihgheehjehjjhghijhjhhaaaa",
"aaaahhihhjhghhhhjehhhhghjhhehhaaaa",
"aaaaahhjhhhhhhiiiiiihhhhhhjhhaaaaa",
"aaaaaahiihiiiiiifgiiiijjehehaaaaaa",
"aaaaaahhhjfgiiiiiiiiiifgeehhaaaaaa",
"aaaaaaahijiiiihhhhhhiijjeehaaaaaaa",
"aaaaaaahihhhhhiijjiihhhhhehaaaaaaa",
"aaaaaaahhjiiiiijfgeiiijjehhaaaaaaa",
"aaaaaaahijiiiijffggeiijjeehaaaaaaa",
"aaaaaaahifgiiijffggeiijfgehaaaaaaa",
"aaaaaaahifgiiiijggeiiijfgehaaaaaaa",
"aaaaaaahiggiiiiieeiiiijggehaaaaaaa",
"aaaaaaahijiiiihhhhhhiijjeehaaaaaaa",
"aaaaaaahijhhhhiiiiiihhhheehaaaaaaa",
"aaaaaaahihjiiihhhhhhijjeeehaaaaaaa",
"aaaaaaahhiihhhiiiiiihhheehhaaaaaaa",
"aaaaaaaahhhijiiiiiiijeehhhaaaaaaaa",
"aaaaaaaaaahhhhhhhhhhhhhhaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const white_queen:Array = [ 0, 0, 35, 35, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaahhhaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaahjiehaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaahhhaaaaaaaaaaaaaaaa",
"aaaaaaahhaaaaaaaahaaaaaaaaahhaaaaaa",
"aaaaaahjehaaaaaaahaaaaaaaahjehaaaaa",
"aaaaaaahhaaaaaaahehaaaaaaaahhaaaaaa",
"aaaaaaaahaaaaaaahjhaaaaaaaahaaaaaaa",
"aaaaaaaahhaaaaaahjhaaaaaaahhaaaaaaa",
"aaaaaaaahhaaaaaahjhaaaaaaahhaaaaaaa",
"aaaaaaaaahaaaaaahjhaaaaaaahaaaaaaaa",
"aaaaaaaaahhaaaaahjhaaaaaahhaaaaaaaa",
"ahhaaaaaahhaaaaahjhaaaaaahhaaaaahha",
"ahjhaaaaahhaaaaahjhaaaaaahhaaaahjha",
"ahhhaaaaahehaaaheiehaaaahehaaaahhha",
"aahhaaaaahjhaaahjiehaaaahjhaaaahhaa",
"aaahhaaaaahhaaahjiehaaaahhaaaahhaaa",
"aaahjhaaaahehaahjiehaaahehaaahjhaaa",
"aaaahjhaaahjhaahhhhhaaahjhaahjhaaaa",
"aaaaahhaaahhhhaheeehahhhhhahhhaaaaa",
"aaaaahjhaaheeehjjjjjhjeeehhijhaaaaa",
"aaaaaahjhhjjjhhhhhhhhhjjehjehaaaaaa",
"aaaaaahjjhhhheeejheeeehhhhjehaaaaaa",
"aaaaaaahhjeeeiiijheiiieejjhhaaaaaaa",
"aaaaaaahjjiiiiijhfhejjiiijehaaaaaaa",
"aaaaaaahjjjjjhhhhfhhhhjjijehaaaaaaa",
"aaaaaaahjhhhhijhffgheihhhhehaaaaaaa",
"aaaaaaahhjeeeiijhfheiieeeehhaaaaaaa",
"aaaaaaahjjiiiiijhgheiiiiijehaaaaaaa",
"aaaaaaahjjiiijjjjhejjjiiijehaaaaaaa",
"aaaaaaahjjjjjhhhhhhhhhjjjjehaaaaaaa",
"aaaaaaahjhhhhjjjjjjjjehhhhehaaaaaaa",
"aaaaaaahhejjjjeeeeeeeeeeeehhaaaaaaa",
"aaaaaaaahhhhhhhhhhhhhhhhhhhaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const white_rook:Array = [ 4, 7, 28, 28, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaahhhhaaaahhhhaaaahhhhaaaa",
"aaaahiehhaaahjehaaahhjehaaaa",
"aaaahjjehhhhhjehhhhhjeehaaaa",
"aaaahhjiiiijjjjjjjjjjehhaaaa",
"aaaaahhhhhhhhhhhhhhhhhhaaaaa",
"aaaaaahejjjjjjjjeeeeehaaaaaa",
"aaaaaahhhhhhhhhhhhhhhhaaaaaa",
"aaaaaahihjiiehjiiijhehaaaaaa",
"aaaaaahihjiiehjiiijhehaaaaaa",
"aaaaaahihjjjehjjjjjhehaaaaaa",
"aaaaaahhhhhhhhhhhhhhhhaaaaaa",
"aaaaaahiiiehijiiehijehaaaaaa",
"aaaaaahiiiehiijiehijehaaaaaa",
"aaaaaahjjjehjjjjehjjehaaaaaa",
"aaaaaahhhhhhhhhhhhhhhhaaaaaa",
"aaaaaahiehiiiehiiiehehaaaaaa",
"aaaaaahiehiiiehiiiehehaaaaaa",
"aaaaaahjehjjjehjjjehehaaaaaa",
"aaaaaahhhhhhhhhhhhhhhhaaaaaa",
"aaaaaahiiehiiiiiehjeehaaaaaa",
"aaahhhhhhhhhhhhhhhhhhhhhhaaa",
"aaahiiiiiiiiiiiiiiiijjeehaaa",
"ahhhhhhhhhhhhhhhhhhhhhhhhhha",
"ahiiiiiiiiiiiiiiiiiiiijjeeha",
"ahiijjjjjjjjjjjjjjjjjjjjeeha",
"ahhhhhhhhhhhhhhhhhhhhhhhhhha",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const white_bishop:Array = [ 7, 4, 23, 30, 
"aaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaahhhaaaaaaaaaa",
"aaaaaaaaahjeehaaaaaaaaa",
"aaaaaaaaahjiehaaaaaaaaa",
"aaaaaaaaaahehaaaaaaaaaa",
"aaaaaaaaahehehaaaaaaaaa",
"aaaaaaaahjjeeehaaaaaaaa",
"aaaaaaahjiiiijehaaaaaaa",
"aaaaaahjiijheijehaaaaaa",
"aaaaaahjijjheijehaaaaaa",
"aaaaahjijhhhhhejehaaaaa",
"aaaaahjiiejheeijehaaaaa",
"aaaaahjiiijheiijehaaaaa",
"aaaaahjiiijheiijehaaaaa",
"aaaaahjjiijheijeehaaaaa",
"aaaaaahjiiiiiijehaaaaaa",
"aaaaaahjjjjjjeeehaaaaaa",
"aaaaaaahjhhhhhehaaaaaaa",
"aaaaaaahjiiiiiehaaaaaaa",
"aaaaaaahjjjjjeehaaaaaaa",
"aaaaaaaahjhhhehaaaaaaaa",
"aaaaaaaahjiiiehaaaaaaaa",
"aaaaaaaaahjiihaaaaaaaaa",
"aaaaaaaaaahhhaaaaaaaaaa",
"aaaaaaaaahjhehaaaaaaaaa",
"aaaaaaaahjehjehaaaaaaaa",
"aahhhaahjehahjehaahhhaa",
"aheeeheehhaaahheeheeeha",
"ahaaahhhaaaaaaahhhaaaha",
"aaaaaaaaaaaaaaaaaaaaaaa"
];

public const white_knight:Array = [ 3, 5, 29, 30, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaahaaaaaaaaaaaaaaaa",
"aaaaaaaahhaahhaaaaaaaaaaaaaaa",
"aaaaaaaaahhahehhhaaaaaaaaaaaa",
"aaaaaaaaaehhhhhehhhaaaaaaaaaa",
"aaaaaaaaahhjjjjieehhaaaaaaaaa",
"aaaaaaaahhjiiiiiiiehhaaaaaaaa",
"aaaaaaahhjjhheiiiiiehhaaaaaaa",
"aaaaaahhjejeiiiiiiijehhaaaaaa",
"aaaaahhjeiiiiiiiieijehhaaaaaa",
"aaaahhjhiiiiiiiijeijehhaaaaaa",
"aaahhjhiiiiiiiiijhiijehhaaaaa",
"aahhjhiiiiiiiijjhiiijehhaaaaa",
"ahhjeiiiiijjjeeehiieijehhaaaa",
"ahjeiiiijjeehhhhiijhijehhaaaa",
"ahjihhjjehhhaahiijhiijehhaaaa",
"ahhjhihhhaaaaahjjhiiiijehhaaa",
"aahhjhhaaaaaahhhhiiiiijehhaaa",
"aaaaaaaaaaaahhjiiiiiiijehhaaa",
"aaaaaaaaaaahhjiiiiiiiiijehhaa",
"aaaaaaaaaahhjiiiiiiiiiijehhaa",
"aaaaaaaahhhjiiiiiiiiiiijehhaa",
"aaaaaaahhjiiiiiiiiiiiiijehhaa",
"aaaaahhhjiiiiiiiiiiiiiiijehha",
"aaaahhjiiiiiiiiiiiiiiiiijehha",
"aaahhjiiiiiiiiiiiiiiiiiijehha",
"aahhjiiiiiiiiiiiiiiiiiiijehha",
"aahjjjjjjjjjjjjjjjjjjjjjjehha",
"aahhhhhhhhhhhhhhhhhhhhhhhhhha",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const white_pawn:Array = [ 8, 5, 19, 30, 
"aaaaaaaaaaaaaaaaaaa",
"aaaaaaaahhhaaaaaaaa",
"aaaaaaahjjjhaaaaaaa",
"aaaaaahjiijehaaaaaa",
"aaaaaahjjjjehaaaaaa",
"aaaaaaaheeehaaaaaaa",
"aaaaaaaahhhaaaaaaaa",
"aaaaaaaheeehaaaaaaa",
"aaaaaahjjjjehaaaaaa",
"aaaaahjjiijjhhaaaaa",
"aaaahjjiiiijehhaaaa",
"aaahjjiiiiijeehhaaa",
"aaahhhhhhhhhhhhhaaa",
"aaaaaaahehhhaaaaaaa",
"aaaaaahjjjjjhaaaaaa",
"aaaaahjjiiijehaaaaa",
"aaaaahjjiiijehaaaaa",
"aaaahjjiiiijeehaaaa",
"aaaahjjiiiijeehaaaa",
"aaaahjjiiiijeehaaaa",
"aaaahjjiiiijeehaaaa",
"aaaaahjiiijjehaaaaa",
"aaaaahjiijeeehaaaaa",
"aaaaaahjeeehhaaaaaa",
"aaaahhhhhhhhhhhaaaa",
"aaahjejjjjjjjehhaaa",
"aahjjiiiiiijieehhaa",
"ahjjjjjjjjjeeeeehha",
"ahhhhhhhhhhhhhhhhha",
"aaaaaaaaaaaaaaaaaaa"
];

public const black_king:Array = [ 1, 0, 34, 35, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaeeeeaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaehhhaaaaaaaaaaaaaaa",
"aaaaeehhhaaaaaahklhaaaaaaehhhhaaaa",
"aaaehklhhhhaaaahllhaaaaehhhklhhaaa",
"aaeehhhhhhhhhaahhhhaaehhhhhhhhhhaa",
"ajehhhjhhhhhhhhhhhhhhhhhhhhehhhhha",
"ajhhhjjjjhhhhhhhhhhhhhhhheeeehhhha",
"ajehhjehjjjhhhhhhhhhhhhjjeehehhhha",
"ajehhjehhhjjjjhhhhhhjjjjehhhehhhha",
"ajehhjjehhhhhjjhhhhjjehhhhheehhhha",
"ajehhhjehhhhhhjhklhjehhhhhhehhhhha",
"aaehhhjjehhhhhjhllhjehhhhheehhhhaa",
"aaehhhhjehhhhhjhhhhjehhhhhehhhhhaa",
"aaaeklhjjehhhhjhhhhjehhhheehllhaaa",
"aaaeehhhjehhhhjhhhhjehhhhehhhhhaaa",
"aaaaehhhjjehhhjhhhhjehhheehhhhaaaa",
"aaaaehhhhjjjjjjhhhhjjjjjehhhhhaaaa",
"aaaaahhhhhhhhhhhhhhhhhhhhhhhhaaaaa",
"aaaaaahhhhhhhhhhklhhhhhhhhhhaaaaaa",
"aaaaaahhhhhhhhhhhhhhhhhhhhhhaaaaaa",
"aaaaaaajekhhhhhhjjhhhhhhkhhaaaaaaa",
"aaaaaaajehhhjjjjhhmmjjhhhhhaaaaaaa",
"aaaaaaajejjjhhhhhhhhhhjeehhaaaaaaa",
"aaaaaaajmhhhhhhhkkhhhhhhhehaaaaaaa",
"aaaaaaajehhhhhhkkllhhhhhhhhaaaaaaa",
"aaaaaaajekhhhhhhllhhhhhhkhhaaaaaaa",
"aaaaaaajkklhhhhhhhhhhhhkklhaaaaaaa",
"aaaaaaajelhhhhhhjjhhhhhhlhhaaaaaaa",
"aaaaaaajehhhmmmmhhmmjjhhhhhaaaaaaa",
"aaaaaaajejjjhhhhhhhhhhjeehhaaaaaaa",
"aaaaaaajmhhhhhhhhhhhhhhhhehaaaaaaa",
"aaaaaaaahhhhhhhhhhhhhhhhhhaaaaaaaa",
"aaaaaaaaaahhhhhhhhhhhhhhaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const black_queen:Array = [ 0, 0, 35, 35, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaahhhaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaahehhhaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaahhhaaaaaaaaaaaaaaaa",
"aaaaaaahhaaaaaaaahaaaaaaaaahhaaaaaa",
"aaaaaahehhaaaaaaahaaaaaaaahehhaaaaa",
"aaaaaaahhaaaaaaahhhaaaaaaaahhaaaaaa",
"aaaaaaaahaaaaaaahhhaaaaaaaahaaaaaaa",
"aaaaaaaahhaaaaaahhhaaaaaaahhaaaaaaa",
"aaaaaaaahhaaaaaahhhaaaaaaahhaaaaaaa",
"aaaaaaaaahaaaaaahhhaaaaaaahaaaaaaaa",
"aaaaaaaaahhaaaaahhhaaaaaahhaaaaaaaa",
"ahhaaaaaahhaaaaahhhaaaaaahhaaaaahha",
"ahehaaaaahhaaaaahhhaaaaaahhaaaaheha",
"ahhhaaaaahehaaahhhhhaaaahhhaaaahhha",
"aahhaaaaahhhaaahehhhaaaahhhaaaahhaa",
"aaahhaaaaahhaaahmhhhaaaahhaaaahhaaa",
"aaahhhaaaahhhaahjhhhaaahhhaaahhhaaa",
"aaaahhhaaahehaahehhhaaahehaahhhaaaa",
"aaaaahhaaahjhhahehhhahhhjhahhhaaaaa",
"aaaaahhhaahehhhhhhhhhhhehhhhhhaaaaa",
"aaaaaahhhhhhhhhhhhhhhhhhhhhhhaaaaaa",
"aaaaaahhehhhheeeeeeeeehhhhhhhaaaaaa",
"aaaaaaahjeeeejjjjjjjjjeeeeehaaaaaaa",
"aaaaaaahjjmmmhhhjhjhhhjjeeehaaaaaaa",
"aaaaaaahehhhhhhjhkhjhhhhhhhhaaaaaaa",
"aaaaaaahjhhhhhjhkklhjhhhhhhhaaaaaaa",
"aaaaaaahehhjjjjhkklhjjjjhhhhaaaaaaa",
"aaaaaaahjmmhhhhjhlhehhhhejehaaaaaaa",
"aaaaaaahehhhhhhhjhehhhhhhhhhaaaaaaa",
"aaaaaaahehhhhhmmmjjjjhhhhhhhaaaaaaa",
"aaaaaaahehjjjjhhhhhhhjjjehhhaaaaaaa",
"aaaaaaahjjhhhhhhhhhhhhhhheehaaaaaaa",
"aaaaaaaahhhhhhhhhhhhhhhhhhhaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const black_rook:Array = [ 4, 7, 28, 28, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaahhhhaaaahhhhaaaahhhhaaaa",
"aaaahjhhhaaahjhhaaahhhhhaaaa",
"aaaahmhhhhhhhjhhhhhhhhhhaaaa",
"aaaahhhjjmjjjmjjjjjeejhhaaaa",
"aaaaahhhhhhhhhhhhhhhhhhaaaaa",
"aaaaaahhhhhhhhhhhhhhhhaaaaaa",
"aaaaaahjjmjjjjjjjjjejhaaaaaa",
"aaaaaahhjhhhhjhhhhhehhaaaaaa",
"aaaaaahhjhhhhjhhhhhehhaaaaaa",
"aaaaaahhjhhhhjhhhhhehhaaaaaa",
"aaaaaahjjmjjjjjjjjeejhaaaaaa",
"aaaaaahhhhhjhhhhhjhhhhaaaaaa",
"aaaaaahhhhhjhhhhhjhhhhaaaaaa",
"aaaaaahhhhhjhhhhhjhhhhaaaaaa",
"aaaaaahjjnjjjjjjjjeejhaaaaaa",
"aaaaaahhhjhhhhjhhhhhehaaaaaa",
"aaaaaahhhjhhhhjhhhhhehaaaaaa",
"aaaaaahhhjhhhhjhhhhhehaaaaaa",
"aaaaaahjjmjjjjjjjjeejhaaaaaa",
"aaaaaahhhhjhhhhhhehhhhaaaaaa",
"aaahhhhhhhhhhhhhhhhhhhhhhaaa",
"aaahjjjjjjjjjjjjjjjjjeejhaaa",
"ahhhhhhhhhhhhhhhhhhhhhhhhhha",
"ahjjjjjjjjjjjjjjjjjjjjjeejha",
"ahhhhhhhhhhhhhhhhhhhhhhhhhha",
"ahhhhhhhhhhhhhhhhhhhhhhhhhha",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const black_bishop:Array = [ 7, 4, 23, 30, 
"aaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaahhhaaaaaaaaaa",
"aaaaaaaaahejhhaaaaaaaaa",
"aaaaaaaaahehhhaaaaaaaaa",
"aaaaaaaaaahhhaaaaaaaaaa",
"aaaaaaaaahhhhhaaaaaaaaa",
"aaaaaaaahhehhhhaaaaaaaa",
"aaaaaaahhehhhhhhaaaaaaa",
"aaaaaahhmhhhhhhhhaaaaaa",
"aaaaaahjhhhjhhhhhaaaaaa",
"aaaaahhjhhhmhhhhhhaaaaa",
"aaaaahehhjmmjehhhhaaaaa",
"aaaaahehhhhmhhhhhhaaaaa",
"aaaaahhhhhhjhhhhhhaaaaa",
"aaaaahhhhhhjhhhhhhaaaaa",
"aaaaaahhhhhehhhhhaaaaaa",
"aaaaaahhhhhhhhhhhaaaaaa",
"aaaaaaahhhhhhhhhaaaaaaa",
"aaaaaaahjjmmjeehaaaaaaa",
"aaaaaaahhhhhhhhhaaaaaaa",
"aaaaaaaahhhhhhhaaaaaaaa",
"aaaaaaaahhmjehhaaaaaaaa",
"aaaaaaaaahhhhhaaaaaaaaa",
"aaaaaaaaaahhhaaaaaaaaaa",
"aaaaaaaaahehhhaaaaaaaaa",
"aaaaaaaahehhhhhaaaaaaaa",
"aaeehaahehhahhhhaahhhaa",
"ahhhhhhhhhaaahhhhhhhhha",
"ahaaahhhaaaaaaahhhaaaha",
"aaaaaaaaaaaaaaaaaaaaaaa"
];

public const black_knight:Array = [ 3, 5, 29, 30, 
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaahaaaaaaaaaaaaaaaa",
"aaaaaaaahhaahhaaaaaaaaaaaaaaa",
"aaaaaaaaahhahehhhaaaaaaaaaaaa",
"aaaaaaaaaehhhhhjhhhaaaaaaaaaa",
"aaaaaaaaahhhhhhhjjhhaaaaaaaaa",
"aaaaaaaahhhhhhhhhhjhhaaaaaaaa",
"aaaaaaahhhjehhhhhhhjhhaaaaaaa",
"aaaaaahhhhhhhhhhhhhhjhhaaaaaa",
"aaaaahhhhhhhhhhhhhhhjhhaaaaaa",
"aaaahhhhhhhhhhhhhhhhjhhaaaaaa",
"aaahhhhhhhhhhhhhhhhhhjhhaaaaa",
"aahhhhhhhhhhhhhhehhhhjhhaaaaa",
"ahhhhhhhhhjhhhhhehhhhhjhhaaaa",
"ahhhhhhhhhhjhhhehhhhhhjhhaaaa",
"ahehhehhhhhhaahhhhehhhehhaaaa",
"ahhhehhhhaaaaahhhehhhhhjhhaaa",
"aahhjhhaaaaaahheehhhhhhehhaaa",
"aaaaaaaaaaaahhhhhhhhhhhehhaaa",
"aaaaaaaaaaahhhhhhhhhhhhhehhaa",
"aaaaaaaaaahhhhhhhhhhhhhhjhhaa",
"aaaaaaaahhhhhhhhhhhhhhhhjhhaa",
"aaaaaaahhhhhhhhhhhhhhhhhehhaa",
"aaaaahhhhhhhhhhhhhhhhhhhhjhha",
"aaaahhhhhhhhhhhhhhhhhhhhhjhha",
"aaahhhhhhhhhhhhhhhhhhhhhhjhha",
"aahhhhhhhhhhhhhhhhhhhhhhhjhha",
"aahhhhhhhhhhhhhhhhhhhhhhhehha",
"aahhhhhhhhhhhhhhhhhhhhhhhhhha",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
];

public const black_pawn:Array = [ 8, 5, 19, 30, 
"aaaaaaaaaaaaaaaaaaa",
"aaaaaaaahhhaaaaaaaa",
"aaaaaaaheehhaaaaaaa",
"aaaaaahenjhhhaaaaaa",
"aaaaaahhhhhhhaaaaaa",
"aaaaaaahhhhhaaaaaaa",
"aaaaaaaahhhaaaaaaaa",
"aaaaaaahhhhhaaaaaaa",
"aaaaaaheeeehhaaaaaa",
"aaaaahenjhhhhhaaaaa",
"aaaahjehhhhhhhhaaaa",
"aaahehhhhhhhhhhhaaa",
"aaahhhhhhhhhhhhhaaa",
"aaaaaaahhhhhaaaaaaa",
"aaaaaaheeeehhaaaaaa",
"aaaaahjjjhhhhhaaaaa",
"aaaaahjjnhhhhhaaaaa",
"aaaahejmhhhhhhhaaaa",
"aaaahejjhhhhhhhaaaa",
"aaaahehhhhhhhhhaaaa",
"aaaahehhhhhhhhhaaaa",
"aaaaahhhhhhhhhaaaaa",
"aaaaahhhhhhhhhaaaaa",
"aaaaaahhhhhhhaaaaaa",
"aaaahhhhhhhhhhhaaaa",
"aaahjejmmjeeehhhaaa",
"aahjhjmjhhhhhhhhhaa",
"ahjjjhhhhhhhhhhhhha",
"ahhhhhhhhhhhhhhhhha",
"aaaaaaaaaaaaaaaaaaa"
];

public const lab_a:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjjjjjhhjde",
"djjjhhhhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjhhhhhjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_b:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhhhhjjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_c:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_d:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjjjjjhhjde",
"djjjjjjhhjde",
"djjjjjjhhjde",
"djjjhhhhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjhhhhhjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_e:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhhhhhjde",
"djjhhjjjjjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_f:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjhhjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjhhhhjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_g:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjhhhhhjde",
"djjjjjjhhjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_h:Array = [ 0, 0, 12, 17, 
"dddddddddddd",
"djjjjjjjjjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhhhhjjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_1:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjhhjjjde",
"djjhhhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_2:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjjjjhhjde",
"djjjjjhhjjde",
"djjjjhhjjjde",
"djjjhhjjjjde",
"djjhhjjjjjde",
"djjhhhhhhjde",
"djjhhhhhhjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_3:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjjjjjhhjde",
"djjjjhhhhjde",
"djjjjhhhjjde",
"djjjjjjhhjde",
"djjjjjjhhjde",
"djjjjjjhhjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_4:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjhhjde",
"djjjjjhhhjde",
"djjjjhhhhjde",
"djjjjhhhhjde",
"djjjhhjhhjde",
"djjjhhjhhjde",
"djjhhjjhhjde",
"djjhhhhhhjde",
"djjjjjjhhjde",
"djjjjjjhhjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_5:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjhhhhhhjde",
"djjhhhhhhjde",
"djjhhjjjjjde",
"djjhhjjjjjde",
"djjhhhhhjjde",
"djjhhjjhhjde",
"djjjjjjhhjde",
"djjjjjjhhjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_6:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjhhjjjjjde",
"djjhhhhhjjde",
"djjhhhhhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_7:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjhhhhhhjde",
"djjhhhhhhjde",
"djjjjjhhjjde",
"djjjjjhhjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjjhhjjjde",
"djjjhhjjjjde",
"djjjhhjjjjde",
"djjjhhjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const lab_8:Array = [ 0, 0, 12, 19, 
"dddddddddddd",
"djjjjjjjjjdj",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhhhhhjde",
"djjjhhhhjjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjhhjjhhjde",
"djjjhhhhjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"djjjjjjjjjde",
"ddddddddddde",
"jeeeeeeeeeee"
];

public const BG0:Array = [ 0, 0, 4, 4, 
"djdj",
"jjjj",
"djdj",
"jjjj"
];

public const LU0:Array = [ 0, 0, 4, 4, 
"hhhh",
"hddd",
"hdjj",
"hdje"
];

public const RU0:Array = [ 0, 0, 4, 4, 
"hhhh",
"dddh",
"jjeh",
"jjeh"
];

public const U0:Array = [ 0, 0, 4, 4, 
"hhhh",
"dddd",
"jjjj",
"eeee"
];

public const L0:Array = [ 0, 0, 4, 4, 
"hdje",
"hdje",
"hdje",
"hdje"
];

public const R0:Array = [ 0, 0, 4, 4, 
"djeh",
"djeh",
"djeh",
"djeh"
];

public const LD0:Array = [ 0, 0, 4, 4, 
"hdje",
"hdjj",
"heee",
"hhhh"
];

public const RD0:Array = [ 0, 0, 4, 4, 
"djeh",
"jjeh",
"eeeh",
"hhhh"
];

public const D0:Array = [ 0, 0, 4, 4, 
"dddd",
"jjjj",
"eeee",
"hhhh"
];

public const LU1:Array = [ 0, 0, 4, 4, 
"jjjj",
"jddd",
"jdjj",
"jdje"
];

public const RU1:Array = [ 0, 0, 4, 4, 
"jjjj",
"dddd",
"jjej",
"ejej"
];

public const U1:Array = [ 0, 0, 4, 4, 
"jjjj",
"dddd",
"jjjj",
"eeee"
];

public const L1:Array = [ 0, 0, 4, 4, 
"jdje",
"jdje",
"jdje",
"jdje"
];

public const R1:Array = [ 0, 0, 4, 4, 
"djej",
"djej",
"djej",
"djej"
];

public const LD1:Array = [ 0, 0, 4, 4, 
"jdje",
"jdjj",
"jeee",
"jjjj"
];

public const RD1:Array = [ 0, 0, 4, 4, 
"djej",
"jjej",
"eeej",
"jjjj"
];

public const D1:Array = [ 0, 0, 5, 4, 
"ddddd",
"jjjjj",
"eeeee",
"jjjjj"
];

public const Lite_Square:Array = [ 0, 0, 4, 4, 
"dddd",
"dddd",
"dddd",
"dddd"
];

public const Dark_Square:Array = [ 0, 0, 4, 4, 
"cccc",
"cccc",
"cccc",
"cccc"
];

public const Scale:Array = [ 0, 0, 28, 8, 
"ahhhhaaaaaaaaaaaaaahoaaaaaaa",
"hhaahhaaaaaaaaaaaaahoaaaaaaa",
"hhaaaaaahhhaaahhhaahhaahhhha",
"hhhhaaahhahhahaahhahhahhaahh",
"aahhhhahhaaaaahhhhahhahhhhhh",
"aaaahhahhaaaahhahhahhahhaaaa",
"hhaahhahoahhahhahhahhahhaahh",
"ahhhhaaahhhaaahhhhahhaahhhha"
];

public const Scalex1:Array = [ 0, 0, 20, 16, 
"boooooooooooooooooob",
"ojdddddddddddddddjoo",
"odpppppppppppppppdjo",
"odpppppqpppqpppppdjo",
"odppppppppppphhppdjo",
"odpqpppppppphhhppdjo",
"odpphhphhpphhhhppdjo",
"odppphhhppphphhppdjo",
"odppphhhppppphhppdjo",
"odpphhphhpppphoppdjo",
"odppppppppppphhppdjo",
"odppppppppppphhppdjo",
"odpppppppqpppppppdjo",
"ojdddddddddddddddjjo",
"ojjjjjjjjjjjjjjjjjoo",
"boooooooooooooooooob"
];

public const Scalex2:Array = [ 0, 0, 20, 16, 
"boooooooooooooooooob",
"ojdddddddddddddddjoo",
"odrrrrrrrrrrrrrrrdjo",
"odrrrrrrrqrrrrrrrdjo",
"odrrrrqrrrrhhhorrdjo",
"odrrrrrrrrhhhhhhrdjo",
"odrhhrhhrrhhrrhhrdjo",
"odrrhhhrrrrrrhhhrdjo",
"odrrhohrrqrrhhhrrdjo",
"odrhhrhhrrrhhrrrrdjo",
"odrrrrrrrrhhhhhhqdjo",
"odrrrrrrrrhhhhhhrdjo",
"odrrrrqrrrrrrrrrrdjo",
"ojdddddddddddddddjjo",
"ojjjjjjjjjjjjjjjjjoo",
"boooooooooooooooooob"
];

public const newgame:Array = [ 0, 0, 62, 18, 
"bboooooooooooooooooooooooooooooooooooooooooooooooooooooooooobb",
"boddddddddddddddddddddddddddddddddddddddddddddddddddddddddddob",
"odssssssssssssssssssssssssssssssssssssssssssssssssssssssssssdo",
"odssssssssssssssqssssssssssssssssssssssssssqssssssssssssssssdo",
"odshhsshhssssssssssssssssssssssssqssssssssssssssssqssssqssssdo",
"odshhsshhsssssssssssssssssssssssssssssssssssssssssssssssssssdo",
"odshhhshhsshhhhsshhsshsshhsssshhhhhsshhhsshhhhhhhhhssshhhhssdo",
"odshhhshhshhsshhshhshhhshhssshhsshhshsshhshhsshhsshhshhsshhsdo",
"odshhshhhshhhhhhshhshhhshhssshhsshhsshhhhshhsshhsshhshhhhhhsdo",
"odshhshhoshhsssssshhhshhhsssshhssohshhshhshhsshhsshhshhsssssdo",
"odshhsshhshhsshhsshhhshhhsssshhsshhshhshhshhsshhsshhshhsshhsdo",
"odshhsshhsshhhhssshhssshhssssshhhhhsshhhhshhsshhsshhsshhhhssdo",
"odsssssssssssssssssssssssssessssshhsssssssssssssssssssssssssdo",
"odssssssssssssssssssssqsssesshhhhhssssssssssssssssssssssssqsdo",
"odsssssqssssssssssssssssqqesssssssssssssssssssssqsssssssssssdo",
"oodddddddddddddddddddddddeoeddddddddddddddddddddddddddddddddeo",
"bojjjjjjjjjjjjjjjjjjjjjjjjohojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjob",
"bboooooooooooooooooooooooooooooooooooooooooooooooooooooooooobb"
];

public const takeback:Array = [ 0, 0, 62, 18, 
"bboooooooooooooooooooooooooooooooooooooooooooooooooooooooooobb",
"boddddddddddddddddddddddddddddddddddddddddohodddddddddddddddob",
"odttttttttttttttttttttttttttttttttttttttttttotttqtttttttttttdo",
"odttttttttttttttttttttttttttttttttttttttttttetttttttttttttttdo",
"odthhhhhhttqtttthhtttqtttttttttthhttttqtttttttttttthhtttttttdo",
"odttthhttttttttthhtttttttttttttthhttttttttttttttttthottttqttdo",
"odttthhtttthhhtthhtthhtthhhhtttthhhhhttthhhttthhhtthotthhtttdo",
"odttthhttthtthhthhthhtthhtthhttthhtthothtthhthhthhthhthhttttdo",
"odqtthhtttthhhhthhhhttthhhhhhttthhtthhtthhhhthhtttthhhhtttttdo",
"odttthhttthhthhthohhhtthhttttttthhtthhthhthhthhtttthhhhhttttdo",
"odttthhttthhthhthhthhtthhtthhttthhtthhthhthhthhthhthhthhttttdo",
"odttthhtttthhhhthhtthhtthhhhtttthhhhhttthhhhtthhhtthhtthhtttdo",
"odttttttttttttttttttttttttttttttttttttttttttttttttttttttttttdo",
"odqttttttttttttttttttqttttttqtttttttttttttttttttttttttttttttdo",
"odttttttqttttttttttttttttttttttttttttttttttttttettqtttttttttdo",
"ooddddddddddddddddddddddddddddddddddddddddddddddohddddddddddeo",
"bojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjoojjjjjjjjjob",
"bboooooooooooooooooooooooooooooooooooooooooooooooooooooooooobb"
];

public const selfgame:Array = [ 0, 0, 62, 18, 
"bboooooooooooooooooooooooooooooooooooooooooooooooooooooooooobb",
"boddddddddddddddddddddddddddddddddddddddddddddddddddddddddddob",
"oduuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuudo",
"oduuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuudo",
"oduuuuhhhhuuuuuuuuuhhuuhhhuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuudo",
"oduuuhhuuhhuuuuuuuuhhuhhuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuqdo",
"oduuuhhuuuuuuhhhhuuhhhhhhuuhhhhhuuhhhuuhhhhhhhhhuuuhhhhuuuuudo",
"oduuuhhhhuuuhhuuhhuhhuhhuuhhuuhhuhuuhhuhhuuhhuuhhuhhuuhhuuuudo",
"oduuuuuhhhhuhhhhhhuhhuhhuuhouuhhuuhhhhuhhuuhhuuhhuhhhhhhuuuudo",
"oduuuuuuuhhuhhuuuuuhhuhhuuhhuuhhuhhuhhuhhuuohuuhhuhouuuuuuuudo",
"oduuuhhuuhhuhhuuhhuhhuhhuuhhuuhhuhhuhhuhhuuhhuuhhuhhuuhhuuuqdo",
"odquuuhhhhuuuhhhhuuhhuhhuuuhhhhhuuhhhhuhhuuhhuuhhuuhhhhuuuuudo",
"oduuuuuuuuuuuuuuuuuuuuuuuuuuuuhhuuuuuuuuuuuuuuuuuuuuuuuuuuuudo",
"odueuuuuuuuuuuuuuuuuuuuuuuhhhhhuuuuuuuuuuuuuuuuuuuuuuuuuuquudo",
"oduueuuquuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuudo",
"ooddoeddddddddddddddddddddddddddddddddddddddddddddddddddddddeo",
"bojjjoojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjob",
"bboooooooooooooooooooooooooooooooooooooooooooooooooooooooooobb"
];

public const sfredlt:Array = [ 0, 0, 5, 5, 
"uufuu",
"ufggu",
"fffgf",
"ugggu",
"ddfdd"
];

public const AI:Array = [ 0, 0, 11, 8, 
"aavvhaaavha",
"aavvhaaavha",
"avhavhaavha",
"avhavhaavha",
"avhavhaavha",
"vvvvvvhavha",
"vhaaavhavha",
"vhaaavhavha"
];

public const brain0:Array = [ 0, 0, 25, 16, 
"bbbbbbbbbhhhhhhbbbbbbbbbb",
"bbbbbhhhhkggkghhhhhhhbbbb",
"bbbhhgggggghhoggggggghbbb",
"bbhhkggggghgkgggggggghhbb",
"bhkggggghhwhggggggghhghhb",
"bhggggghggkxgggggggyhgghb",
"hkgggggggggggggggkkkykgkh",
"hhggggggggggggggghhhhhhkh",
"hggkkhhhhkggggggggggggzhh",
"hhggggghggggggggghhkgggkh",
"bhggggghgggggggkhhhgggghb",
"bbhgggghhggggghhhggggghbb",
"bbbhhhhhyhhhhhhhkgkgghbbb",
"bbbbbbbbbbbbbbbbhgkghbbbb",
"bbbbbbbbbbbbbbbbbhghhbbbb",
"bbbbbbbbbbbbbbbbbbhhbbbbb"
];

public const brain1:Array = [ 0, 0, 25, 16, 
"bbbbbbbbbhhhhhhbbbbbbbbbb",
"bbbbbhhhhkffAfhhhhhhhbbbb",
"bbbhhffffffhhofffffffhbbb",
"bbhhAfffffhfkffffffffhhbb",
"bhAfffffhhwhfffffffhhfhhb",
"bhfffffhffkxfffffffyhffhb",
"hkfffffffffffffffkkkykfBh",
"hhfffffffffffffffhhhhhhkh",
"hffkkhhhhAffffffffffffzhh",
"hhfffffhfffffffffhhBfffkh",
"bhfffffhfffffffkhhhffffhb",
"bbhffffhhfffffhhhfffffhbb",
"bbbhhhhhyhhhhhhhkfkffhbbb",
"bbbbbbbbbbbbbbbbhfkfhbbbb",
"bbbbbbbbbbbbbbbbbhfhhbbbb",
"bbbbbbbbbbbbbbbbbbhhbbbbb"
];

public const depth:Array = [ 0, 0, 34, 10, 
"aaaahhaaaaaaaaaaaaaaahhaahhaaaaaaa",
"aaaahhaaaaaaaaaaaaaaahhaahhaaaaaaa",
"ahhhhhaahhhhaahhhhhahhhhahhhhhaahh",
"hhaahhahhaahhahhaahhahhaahhaahhahh",
"hhaaohahhhhhhahhaahhahhaahhaaohaaa",
"hhaahhahhaaaaahhaahhahhaahhaahhaaa",
"hhaahhahhaahhahhaahhahhaahhaahhahh",
"ahhhhhaahhhhaahhhhhaaahhahhaahhahh",
"aaaaaaaaaaaaaahhaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaahhaaaaaaaaaaaaaaaaaa"
];

public const timesec:Array = [ 0, 0, 40, 10, 
"ahhaahhaaaaaaaaaaaaaaaaaaaaahaaaaaahaaaa",
"ahhaaaaaaaaaaaaaaaaaaaaaaaahaaaaaaaahaaa",
"hhhhahhahhhhhhhhhaaahhhhaahhaahhhhaahahh",
"ahhaahhahhaahhaahoahhaahhahhahhaahhahChh",
"ahhaahhahhaahhaahhahhhhhoahhahhhhaaahhaa",
"ahoaahhahoaahhaahhahhaaaaahhaaahhhhahhaa",
"ahhaahhahhaahhaahhahhaahhahhahhaahhahChh",
"aahhahhahhaahhaahhaahhhhaaahaahhhhaahahh",
"aaaaaaaaaaaaaaaaaaaaaaaaaaahaaaaaaahhaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaahaaaaaahaaaa"
];

public const plus:Array = [ 0, 0, 14, 14, 
"bboooooooooobb",
"boddddddddDoob",
"odDqDDDDDDDDzo",
"odDDDhhhDqDDCo",
"odDDDhhhDDDDjo",
"oDDqDhhkDDDDjo",
"oDhhhhhhhhhDjo",
"oDhhhhhhhhhDjo",
"oDDDDhhhDDDDjo",
"oDDDDhhhDDDDjo",
"oDDDDhhhDDDdCo",
"oDDDDDDDDqDdzo",
"boDDDkkddddoob",
"bboooooooooobb"
];

public const minus:Array = [ 0, 0, 14, 14, 
"bboooooooooobb",
"bodddddAAAAoob",
"odAAAAAAAAAAzo",
"odAAAAAAqAAACo",
"odAAAqAAAAAAjo",
"oAAAvvvvvvvAjo",
"oAhhhhhehhhAjo",
"oAhhhhhhhhhAjo",
"oAvvvvAAAAAAjo",
"oAAAAAAAAAAdjo",
"oAAAAAqAAAAdCo",
"oAAqAAAAAAAdzo",
"boAAAAvvdddoob",
"bboooooooooobb"
];


	public const List:Array = [
/*0*/	white_king,
/*1*/	white_queen,
/*2*/	white_rook,
/*3*/	white_bishop,
/*4*/	white_knight,
/*5*/	white_pawn,
/*6*/	black_king,
/*7*/	black_queen,
/*8*/	black_rook,
/*9*/	black_bishop,
/*10*/	black_knight,
/*11*/	black_pawn,
/*12*/	lab_a,
/*13*/	lab_b,
/*14*/	lab_c,
/*15*/	lab_d,
/*16*/	lab_e,
/*17*/	lab_f,
/*18*/	lab_g,
/*19*/	lab_h,
/*20*/	lab_1,
/*21*/	lab_2,
/*22*/	lab_3,
/*23*/	lab_4,
/*24*/	lab_5,
/*25*/	lab_6,
/*26*/	lab_7,
/*27*/	lab_8,
/*28*/	BG0,
/*29*/	LU0,
/*30*/	RU0,
/*31*/	U0,
/*32*/	L0,
/*33*/	R0,
/*34*/	LD0,
/*35*/	RD0,
/*36*/	D0,
/*37*/	LU1,
/*38*/	RU1,
/*39*/	U1,
/*40*/	L1,
/*41*/	R1,
/*42*/	LD1,
/*43*/	RD1,
/*44*/	D1,
/*45*/	Lite_Square,
/*46*/	Dark_Square,
/*47*/	Scale,
/*48*/	Scalex1,
/*49*/	Scalex2,
/*50*/	newgame,
/*51*/	takeback,
/*52*/	selfgame,
/*53*/	sfredlt,
/*54*/	AI,
/*55*/	brain0,
/*56*/	brain1,
/*57*/	depth,
/*58*/	timesec,
/*59*/	plus,
/*60*/	minus
	];

	}
}
